# Site settings
title: Grayscale
email: fabian.loeschner@outlook.com
url: https://w1th0utnam3.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Fabian Löschner

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/w1th0utnam3
  - title: 500px
    url: https://500px.com/w1th0utnam3
  - title: github
    url: https://github.com/w1th0utnam3

# Build settings
markdown: kramdown
permalink: pretty
